services:
  - type: web
    name: wellness-app-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_BASE_URL
        fromService:
          type: web
          name: wellness-app-backend
          property: host
        
  - type: web
    name: wellness-app-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: wellness-app-db
          property: connectionString
          
databases:
  - name: wellness-app-db
    databaseName: wellness_app
    user: wellness_user